### ISSUE TITLE
Tag arm32v7-latest not found in repository docker.io/robertslando/zwave2mqtt

### ISSUE THREAD

**Issue by dkjsj** [robertsLando/Zwave2Mqtt-docker#1]
I'm having trouble pulling the docker image with the tag arm32v7-latest. How to solve?

**Comment by robertsLando** [comment]
Just tested on my pi using commands: 

```
docker pull robertslando/zwave2mqtt:arm32v7-latest
docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 --mount source=zwave2mqtt,target=/usr/src/app/store robertslando/zwave2mqtt:arm32v7-latest
```

And it works. Please provide log output with errors for support. 

If you used a voume as persistence in v 1.0.0 please follow [docs](https://github.com/robertsLando/Zwave2Mqtt-docker#upgrade-from-100-to-110) to upgrade to version `1.1.0`

**Comment by dkjsj** [comment]
The error/output that's produced is:

--
docker pull robertslando/zwave2mqtt:arm32v7-latest
arm32v7-latest: Pulling from robertslando/zwave2mqtt

2ff15fa1acd9: Pulling fs layer                                                                                                                                          9f24eb4bf031: Pulling fs layer                                                                                                                                          e518d73874e2: Pulling fs layer                                                                                                                                          e01674ce4633: Pulling fs layer                                                                                                                                          ad71d3975f1f: Pulling fs layer                                                                                                                                          42bb000eb925: Pulling fs layer                                                                                                                                          c13b71e9ea07: Pulling fs layer                                                                                                                                          6042f2a3d790: Pulling fs layer                                                                                                                                          2afd7e761eb4: Pulling fs layer                                                                                                                                          7e8870146c0b: Pulling fs layer                                                                                                                                          7036c3f8abd9: Pulling fs layer                                                                                                                                          e0602f2f6dd2: Already exists                                                                                                                                            Pulling repository docker.io/robertslando/zwave2mqtt
Tag arm32v7-latest not found in repository docker.io/robertslando/zwave2mqtt
--

And log's from daemon.log:

May  9 15:41:27 raspberrypi docker[2108]: time="2019-05-09T15:41:27.266679658+01:00" level=error msg="error copying from layer download progress reader: download canceled Head https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/a3/a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4/data?verify=1557415876-2l4BJZdKOdTNQOr3gZNcWKB5ef0%3D: net/http: TLS handshake timeout"

So, yes - might be an error from proxy infront off hub.docker.com

**Comment by robertsLando** [comment]
@dkjsj I think yes it is most likely an error with http proxy or something else, I can successfully fetch the tag and it exists as it is present on dockerhub so I will close this issue
