### ISSUE TITLE
multi-arch image for 2.1.0 release?

### ISSUE THREAD

**Issue by billimek** [robertsLando/Zwave2Mqtt-docker#10]
zwave2mqtt version 2.1.0 was just released and I see an associated `robertslando/zwave2mqtt:amd64-2.1.0-dev` image on docker hub, but am wondering if there will also be a multi-arch image built & published as well?

**Comment by billimek** [comment]
reached-out via Slack, don't think an issue is needed.

An image is being built.

**Comment by robertsLando** [comment]
Unfortunally the build seems broken on others archs and only that build goes successfully, I’m investigating

Daniel

**Comment by robertsLando** [comment]
@billimek It is ready now :)
