### ISSUE TITLE
How to run at boot on a pi 4?

### ISSUE THREAD

**Issue by crxporter** [robertsLando/Zwave2Mqtt-docker#14]
Hi I'm hoping you've got a minute to give some advice here, this is my first time trying a docker package and I'm struggling a bit to get things running.

Hardware: pi 4 and zooz USB stick

What I've done so far:
1. try to build openZwave from the source (I think this worked)
2. try to install zwave2mqtt packaged version from github (this did not work)
3. install zwave2mqtt the npm way (this worked)

At this point I was able to get the program running, pair a couple of devices, etc. Looks great. Now I want it to run on startup and keep itself updated. If I understand docker correctly, the docker-compose way is supposed to do this.

4. install docker (pi script)
5. install docker-compose (pip way)
6. run `sudo docker-compose up`

This runs but it isn't creating the settings, scenes, or nodes json files (shows "not found" for those files). It is also running at startup - but still without any of the setup files. 

-----------------
That's where I'm at right now. I'll be scrapping that SD card image this evening and starting fresh. If you can review and correct me where I've missed things I would greatly appreciate it. I think the steps are:
1. install docker
2. let the user "pi" have docker access 
3. install docker-compose (I'll use the pip way)
4. run the `docker-compose up` with this repo's yaml file

Is that it? What did I miss that made my configuration files not be found (or created)?

Final question: in the future when I want to update to the newest versions, how do I do that?

**Comment by robertsLando** [comment]
`docker-compose up -d` will do the job

**Comment by crxporter** [comment]
That will... fix my missing files?

Or update the container?

**Comment by robertsLando** [comment]
Follow this guide to install docker: https://howchoo.com/g/nmrlzmq1ymn/how-to-install-docker-on-your-raspberry-pi

Than  create a directort `z2m` and create an empty `store` directory inside it, in `z2m directory create this https://github.com/robertsLando/Zwave2Mqtt-docker#run-as-a-service `docker-compose.yml` file and run  `docker-compose up -d`

All configuration files will be stored in store folder

**Comment by crxporter** [comment]
Thank you very much! I'll try this tonight and re open if I have more problems.

**Comment by mbhoek** [comment]
@robertsLando If I try to run zwave2mqtt on a RPI4, I get the following error on `docker-compose up`:
```
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

I'm using Ubuntu 19.10 eoan (64-bit Server) availabe at [the Ubuntu downloads page](https://ubuntu.com/download/raspberry-pi). I'm using docker 19.03.8 (installed using the 'get.docker.com' script).

I'm guessing this is an architecture thing? Or is there something I can do to fix this?

**EDIT: installing the 32-bit version of Ubuntu 19.10 eoan (Server) solved this.**
