### ISSUE TITLE
[ARM64v8] no matching manifest for linux/arm64/v8 in the manifest list entries.

### ISSUE THREAD

**Issue by Gsyltc** [robertsLando/Zwave2Mqtt-docker#15]
Hi,

Can you produce an linux/arm64/v8 latest version please (ODROID C2, N2).

arm64 version does not match with requierement :

`docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

`docker manifest annotate ... --os linux --arch arm64 **--variant v8**` (not amrv8)

Thanks

P.s : robertslando/zwave2mqtt:arm64v8-3.0.1 is ok for arm64/v8

**Comment by robertsLando** [comment]
I sincerly don't know why this happens... By checking manifest I get:

![Schermata da 2020-03-13 08-42-39](https://user-images.githubusercontent.com/11502495/76600179-af17c080-6506-11ea-84db-ad5ce49503fd.png)

**Comment by robertsLando** [comment]
@Gsyltc Would you like to submit a fix to the build script to support that?

I think its just matter of adding an annotate to the manifest

Check https://github.com/robertsLando/Zwave2Mqtt-docker/blob/master/bin/build.sh#L39

**Comment by magpern** [comment]
@robertsLando I'm not so uptodate with the docker manifest and how it works, but I could learn! I'll start the learning immediately :)

But untill then, I took a look at zigbee2mqtt how it looks there. It only has a `linux/arm64` tag, and this one works on the Orange Pi 3
https://hub.docker.com/r/koenkk/zigbee2mqtt/tags

Comparing to your tags in DockerHub you have a more specific tag, `linux/arm64/armv8`

**Comment by magpern** [comment]
zigbee2mqtt is built by azure-pipeline and in that script it says like this
```json
buildx build \
      --build-arg COMMIT=$(git rev-parse --short HEAD) \
      --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
      -f docker/Dockerfile \
      --push \
      -t koenkk/zigbee2mqtt:latest-dev
```
right now, not sure how that is translated to your build.sh

**Comment by Gsyltc** [comment]
> I think its just matter of adding an annotate to the manifest

Yes, it's only a manifest annotation to add.

In the build sh, platform is configured for linux/arm64/v8, linux/arm64/v6, linux/arm64/v7.

But, the annotation is linux/arm64/armv8, linux/arm64/armv6, linux/arm64/armv7 .

Maybe this works some some platform. But, on Odroid C2, N1 with Armbian the platform need to be linux/arm64/v8.

If you run docker with the version 19.03.X, you can modify the manifest after image is build.
Image for OrangePi works well. 

So I will work on a patch to modify the manifest and I will send you when it's ok

**Comment by magpern** [comment]
@Gsyltc @robertsLando I have fixed it and tested it here https://hub.docker.com/r/magpern/zwave2mqtt/tags

I will create a PR later today

**Comment by robertsLando** [comment]
@magpern happy to review it, thanks! :)

**Comment by magpern** [comment]
@robertsLando how long does it take before DockerHub updates? Is it an automatic update or manual?

**Comment by Gsyltc** [comment]
> @Gsyltc @robertsLando I have fixed it and tested it here https://hub.docker.com/r/magpern/zwave2mqtt/tags
> 
> I will create a PR later today

Thanks. 
After review de the pull request I thinks it will be perfect. :)

For the update, did the pipeline is automaticaly launch ?
@magpern Normally, when the docker push command is launched and finished, it's in the registry. No delay

**Comment by magpern** [comment]
@Gsyltc well, it's 8 hours ago now since the PR was completed. I don't think the automatic build and push to dockerhub works.

**Comment by robertsLando** [comment]
It’s not automatic guys, not yet at least, I need to create a github action for that but for now I prefer doing it manually. I will do it next days

**Comment by robertsLando** [comment]
@magpern @Gsyltc please subscribe to zwave2mqtt slack, I will release a new version today

**Comment by magpern** [comment]
@robertsLando zwave2mqtt slack?

**Comment by robertsLando** [comment]
https://join.slack.com/t/zwave2mqtt/shared_invite/enQtNjc4NjgyNjc3NDI2LTc3OGQzYmJlZDIzZTJhMzUzZWQ3M2Q3NThmMjY5MGY1MTc4NjFiOWZhZWE5YjNmNGE0OWRjZjJiMjliZGQyYmU

**Comment by robertsLando** [comment]
ZwaveMqtt 3.0.2 is available now on docker-hub :tada:

**Comment by Gsyltc** [comment]
It's all good !!! Thanks a lot

**Comment by magpern** [comment]
Thanks! I can confirm it works fine now on Orange Pi 3 with Armbian Bionic with Linux 5.4.20-sunxi64

**Comment by robertsLando** [comment]
Thanks to you for the PR :)

**Comment by awilliam** [comment]
Is this supposed to be fixed permanently or was this a one-off build?

I can pull robertslando/zwave2mqtt:arm64-v8-3.0.3 but if I try latest:
```
# podman pull docker.io/robertslando/zwave2mqtt:latest
Trying to pull docker.io/robertslando/zwave2mqtt:latest...
  no image found in manifest list for architecture arm64, variant v8, OS linux
Error: error pulling image "docker.io/robertslando/zwave2mqtt:latest": unable to pull docker.io/robertslando/zwave2mqtt:latest: unable to pull image: Error choosing an image from manifest list docker://robertslando/zwave2mqtt:latest: no image found in manifest list for architecture arm64, variant v8, OS linux
```

**Comment by robertsLando** [comment]
Could you simply try to pull latest? No need to specify arch

**Comment by awilliam** [comment]
I thought that's what I was trying to do ;)  Sorry, I'm a container newb.  Taking the opposite approach of overriding the defaults does work however:
```
podman pull --override-arch=arm64 docker.io/robertslando/zwave2mqtt:latest
```

Images like `docker.io/library/eclipse-mosquitto` and `docker.io/nodered/node-red` don't require this though, so there's still something funky with the advertised manifest, but I have a workaround now.  Thanks
