### ISSUE TITLE
Request for Unraid 

### ISSUE THREAD

**Issue by Linearburn** [robertsLando/Zwave2Mqtt-docker#17]
could you sumit this for the unraid community apps and add support for the config

**Comment by robertsLando** [comment]
Could you explain more about it?

**Comment by Linearburn** [comment]
So [Unraid ](https://unraid.net/) has a app store kinda like the app store that is on android devices. you can download anything from plugins to docker containers http://image.xvxagaming.com/images/2020/04/10/unraid.png This is a search for MQTT I did. there is nothing like your container on there and I think it would be a great addition.  you can find more info on it here https://forums.unraid.net/topic/38582-plug-in-community-applications/

**Comment by robertsLando** [comment]
@Linearburn I have sign up there but I cannot find how to submit a new app, could you help?

**Comment by Zeron** [comment]
While would be great to see this listed in the UnRaid Community Applications "appstore", you can already use this via UnRaid by doing the following:

1. From Apps, search for zwave2mqtt.  When you get no results, click the "Click Here To Get More Results From DockerHub" link zwave2mqtt by robertslando comes up as the first result, click the install icon
2. Click "Add another Path, Port, Variable, Label or Device", Select Type: Path, Name Appdata, Container path: /usr/src/app/store Host Path: <your app data folder>/zwave2mqtt/  AccessMode: Read/Write
3. Click "Add another Path, Port, Variable, Label or Device", Select Type: Port, Name: Web Interface, Container Port: 8091 Host Port: 8091 Connection Type: TCP
4. Click "Add another Path, Port, Variable, Label or Device", Select Type: Device, Name: ZWave USB Adapter Value: /dev/ttyACM0
5. Click Apply

Open the WebUI by going to http://<your unraid server>:8091

**Comment by robertsLando** [comment]
Did you saw this: https://github.com/madmanmatt/zwave2mqtt-unraid?

**Comment by Linearburn** [comment]
I forgot to send you this  https://github.com/selfhosters/unRAID-CA-templates

**Comment by Linearburn** [comment]
https://github.com/selfhosters/unRAID-CA-templates    This is how to get it listed in the app store

**Comment by robertsLando** [comment]
I sent an email to squid and this is his answer:

```
It's going to be a bit of a PITA since you're not running unRaid currently (I presume).  What you're going to need to do is

 

https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

 

What I would suggest is that you ask Zeron (the guy on GitHub telling peep how to install it) for his xml file (/config/plugins/dockerMan/templates-user/my-zwave2mqtt.xml on the flash drive) and then use that in a separate GitHub repository which you'll give me the URL for. 

 

We can fill in the missing items that he probably never did after he gets you the xml.

 

Alternatively, you *could* manually create an xml for it, but it's not something I'd recommend 

 https://wiki.unraid.net/DockerTemplateSchema

```

Is there anyone that could help with this. @Linearburn?

I'm not using Unraid and I have not time to investigate on this ATM

**Comment by robertsLando** [comment]
Done on z2m side
