### ISSUE TITLE
amd64-3.0.3 missing on dockerhub

### ISSUE THREAD

**Issue by iblis82** [robertsLando/Zwave2Mqtt-docker#18]
Looks like only the arm architecture of 3.0.3 has been built. The amd releases are still on build 3.0.2.
![robertslando_zwave2mqtt Tags - Docker Hub](https://user-images.githubusercontent.com/14071775/79788854-942c3d80-8349-11ea-9a60-120270c01d18.png)

**Comment by robertsLando** [comment]
@iblis82 Working on it :) Wait few minutes and it will be available

**Comment by robertsLando** [comment]
Here you are: https://hub.docker.com/layers/robertslando/zwave2mqtt/latest/images/sha256-57e8c8c1d2be76150fc819602ad7dc8ed5dfd3ead1571b5f962d3c784cf52306?context=explore

**Comment by iblis82** [comment]
Thank you :)
