### ISSUE TITLE
Speed up building openzwave by using all processors

### ISSUE THREAD

**Issue by seletz** [robertsLando/Zwave2Mqtt-docker#5]
Trying to rebuild the docker container because of https://github.com/OpenZWave/Zwave2Mqtt/issues/44.
Build is painfully slow on my machine -- adding `-j8` on the openzwave make command helps.

**Comment by robertsLando** [comment]
Just a question, in the option you added, `-j<n>`  `n` should match the number of cores in your machine?

**Comment by robertsLando** [comment]
In that case why don't use `-j${(grep -c processor /proc/cpuinfo)}` for better cross compiling? Not all machine can run 8 jobs simultaniously like yours and this could cause problems when building in other machines (maybe)

**Comment by seletz** [comment]
Yes sure.  Will update and push again.
