### ISSUE TITLE
Repulling latest tag not the lastest 1.1.3 release

### ISSUE THREAD

**Issue by RualdOrdelman** [robertsLando/Zwave2Mqtt-docker#8]
I want to update my ZwaveToMqtt docker container but it looks like there's no new image to pull for the latest tag. 

My docker-compose used:
    image: robertslando/zwave2mqtt:latest

But when recreating of pulling a new image there's no new version. Docker keep using the old image and the 1.1.3 release contains a visible version number in the app and I don't see that. 

When I look at hub.docker.com I see that the last update is 23 days ago.
https://hub.docker.com/r/robertslando/zwave2mqtt

Do I something wrong or have the containers not been updated yet?

**Comment by robertsLando** [comment]
I haven't update docker image to latest release because It is bugged, I'm waiting for openzwave-shared to fix the issue than I will release the 1.4 and also update the docker image too

**Comment by RualdOrdelman** [comment]
Check thanks for doing this great stuff.

**Comment by davidnoyes** [comment]
Will there be a 2.0.0 release to match today’s code release?
Thanks

**Comment by robertsLando** [comment]
I need to rebuild it and create a patch 2.0.1 release as I made a typo in code. Tomorrow or this evening I will release it

Daniel
