### ISSUE TITLE
Feature request: SSL support

### ISSUE THREAD

**Issue by mlankamp** [robertsLando/Zwave2Mqtt-docker#9]
Enable ssl support

**Comment by robertsLando** [comment]
Could you explain better your feature request please?

Daniel

**Comment by mlankamp** [comment]
the vuejs webfrontend runs on port 8091, would be great if this runs with an SSL certificate (like letsencrypt)

**Comment by robertsLando** [comment]
Why not use nginx for this? 

Daniel

**Comment by mlankamp** [comment]
Good point!
